-- Add topic columns to messages table for AI-generated topic labels
-- Migration for REQ-3: Mind Map Visualization Engine

-- Add topic column to store AI-extracted topic label (3-5 words)
ALTER TABLE messages
ADD COLUMN topic TEXT NULL;

-- Add timestamp to track when topic was generated
ALTER TABLE messages
ADD COLUMN topic_generated_at TIMESTAMPTZ NULL;

-- Create index for efficient topic filtering
-- Only indexes rows where topic is not null to save space
CREATE INDEX idx_messages_topic
ON messages(conversation_id, topic)
WHERE topic IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN messages.topic IS 'AI-extracted topic label (3-5 words) for mind map visualization';
COMMENT ON COLUMN messages.topic_generated_at IS 'Timestamp when the topic was generated by AI';
